#
# This file is part of MedShake CCAM NGAP API.
#
# Copyright (c) 2018
# Bertrand Boutillier <b.boutillier@gmail.com>
# http://www.medshake.net
#
# MedShake CCAM NGAP API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# MedShake CCAM NGAP API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with MedShake CCAM NGAP API.  If not, see <http://www.gnu.org/licenses/>.
#
#
#######################################
#
# Documentation
#
# Ensemble des points d'entrée dans l'api documentés au format yaml
#
#######################################

ngap:
  "/ngap/actes/{code}/":
    description: "Obtenir les informations générales sur l'acte NGAP à partir du code de l'acte."
    tester: "/ngap/actes/MEG/"
    methode: "GET"
  "/ngap/actes/liste/codePrestation/{codePrestation}/":
    description: "Obtenir la liste des prestations NGAP recouvertes par un code prestation agrégé."
    tester: "/ngap/actes/liste/codePrestation/MCX/"
    methode: "GET"
ccam:
  "Actes":
    "/ccam/actes/{code}/":
      description: "Obtenir les informations générales sur l'acte CCAM à partir du code de l'acte."
      tester: "/ccam/actes/BACA008/"
      methode: "GET"
    "/ccam/actes/{code}/{activite}/{phase}/":
      description: "Obtenir les informations détaillées sur un acte CCAM à partir du code acte, du code activité et de du code phase."
      tester: "/ccam/actes/BACA008/1/0/"
      methode: "GET"
    "/ccam/actes/{code}/{activite}/associations/":
      description: "Obtenir les actes associables à cet acte et pour ce code activité."
      tester: "/ccam/actes/LBLD017/1/associations/"
      methode: "GET"
    "/ccam/actes/{code}/executants/":
      description: "Obtenir les executants possibles pour cet acte par code activité."
      tester: "/ccam/actes/HBLD332/executants/"
      methode: "GET"
    "/ccam/actes/{code}/incompatibilites/":
      description: "Obtenir les actes incompatibles avec cet acte."
      tester: "/ccam/actes/HCGA109/incompatibilites/"
      methode: "GET"
    "/ccam/actes/{code}/notes/":
      description: "Obtenir les notes de l'acte."
      tester: "/ccam/actes/LBLD017/notes/"
      methode: "GET"
    "/ccam/actes/{code}/position/":
      description: "Obtenir les informations de positionnement de l'acte dans l'arborescence de la CCAM."
      tester: "/ccam/actes/BACA008/position/"
      methode: "GET"
    "/ccam/actes/{code}/prescripteurs/":
      description: "Obtenir les prescripteurs possibles pour cet acte."
      tester: "/ccam/actes/HBLD332/prescripteurs/"
      methode: "GET"
    "/ccam/actes/{code}/priseEnCharge/":
      description: "Obtenir les conditions de prise en charge pour cet acte."
      tester: "/ccam/actes/HCGA109/priseEnCharge/"
      methode: "GET"
    "/ccam/actes/{code}/voisins/":
      description: "Obtenir les voisins de l'acte dans l'arborescence de la CCAM.<br>NB : aucun filtre n'est appliqué, tous les codes distincts trouvés sont retournés sans préjuger de leur validité."
      tester: "/ccam/actes/BACA008/voisins/"
      methode: "GET"
    "/ccam/actes/rechercher/":
      description: "Obtenir une liste d'actes par recherche texte. Les jockers SQL % et _ sont reconnus et doivent être inclus si besoin dans le texte de recherche. Les paramètres debut et nombre permettent la pagination des résultats."
      tester: "/ccam/actes/rechercher/"
      methode: "POST"
      vars:
        texte:
          exemple: "néphrectomie%surré%"
          description: "chaine à rechercher"
        debut:
          exemple: 0
          description: "rang du 1er résultat à retourner (0 par défaut)"
        nombre:
          exemple: 100
          description: "nombre de résultats à retourner (limité à 100, 10 par défaut)"
  "Modificateurs":
    "/ccam/modificateur/{modificateur}/":
      description: "Obtenir les informations du modificateur par convention PS."
      tester: "/ccam/modificateur/F/"
      methode: "GET"
    "/ccam/modificateurs/liste/{convention}/":
      description: "Obtenir la liste des modicateurs CCAM actifs pour une convention PS."
      tester: "/ccam/modificateurs/liste/9/"
      methode: "GET"
  "Arborescence":
    "/ccam/arborescence/racine/":
      description: "Obtenir les chapitres de 1er niveau dans l'arborescence CCAM."
      tester: "/ccam/arborescence/racine/"
      methode: "GET"
    "/ccam/arborescence/chapitres/chapitre/{chapitre}/":
      description: "Obtenir les informations sur un chapitre CCAM.<br>NB : la liste des actes du chapitre n'est pas filtrée, tous les codes distincts trouvés sont retournés sans préjuger de leur validité."
      tester: "/ccam/arborescence/chapitres/chapitre/2.3.4/"
      methode: "GET"
    "/ccam/arborescence/chapitres/code/{code}/":
      description: "Obtenir les informations sur un chapitre CCAM à portir de son code menu.<br>NB : la liste des actes du chapitre n'est pas filtrée, tous les codes distincts trouvés sont retournés sans préjuger de leur validité."
      tester: "/ccam/arborescence/chapitres/code/154/"
      methode: "GET"
  "Correspondances":
    "/ccam/correspondances/{parametre}/":
      description: "Obtenir le tableau de correspondance entre codes et libellés."
      tester: ""
      methode: "GET"
  "Autres":
    "/ccam/grillesTarifaires/liste/":
      description: "Obtenir la liste des grillesTarifaires et libellés."
      tester: "/ccam/grillesTarifaires/liste/"
      methode: "GET"
