#
# This file is part of MedShake CCAM NGAP API.
#
# Copyright (c) 2018
# Bertrand Boutillier <b.boutillier@gmail.com>
# http://www.medshake.net
#
# MedShake CCAM NGAP API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# MedShake CCAM NGAP API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with MedShake CCAM NGAP API.  If not, see <http://www.gnu.org/licenses/>.
#
#
#######################################
#
# Routes
#
# Ensemble des routes nécessaires à la bonne résolution des url au format yaml
# (Thanks to AltoRouter <http://altorouter.com/> !)
#
#######################################

index: ['GET', '/', 'index']

actesCcam: ['GET', '/ccam/actes/[a:code]/', 'actesCcam']
actesCcamDetails: ['GET', '/ccam/actes/[a:code]/[i:activite]/[i:phase]/', 'actesCcamDetails']
conventionsListe: ['GET', '/ccam/conventions/liste/', 'conventionsListe']
modificateurs: ['GET', '/ccam/modificateurs/liste/[i:convention]/', 'modificateursListe']

actesNgap: ['GET', '/ngap/actes/[a:code]/', 'actesNgap']
actesNgapListerParCodePrestation: ['GET', '/ngap/actes/liste/codePrestation/[a:codePrestation]/', 'actesNgapListerParCodePrestation']
